from django.contrib import admin 
from .models import * 

admin.site.register(Brand)
admin.site.register(Car)
admin.site.register(Option)
admin.site.register(CarOption)
admin.site.register(Image)
admin.site.register(AppUser)
admin.site.register(Modification)
admin.site.register(Category)
admin.site.register(UserCategory)
admin.site.register(Performance)
admin.site.register(Engine)
admin.site.register(Gas)
admin.site.register(Electric)
admin.site.register(Transmission)
admin.site.register(Brake)
admin.site.register(Specification)
admin.site.register(SpecificationEngine)
admin.site.register(Review)
admin.site.register(CategorySpecification)