# Generated by Django 5.1.5 on 2025-01-24 07:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_remove_car_ck_car_releasedate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="emailUser",
            field=models.ForeignKey(
                db_column="emailUser",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
