# Generated by Django 5.1.5 on 2025-01-17 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_remove_car_ck_car_releasedate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="appuser",
            name="last_login",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="last login"
            ),
        ),
    ]
