# Generated by Django 5.1.4 on 2025-01-25 15:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_alter_review_emailuser"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="car",
            name="CK_Car_releaseDate",
        ),
        migrations.RemoveConstraint(
            model_name="review",
            name="CK_Review_date",
        ),
        migrations.AddConstraint(
            model_name="car",
            constraint=models.CheckConstraint(
                condition=models.Q(("releaseDate__lte", datetime.date(2025, 1, 25))),
                name="CK_Car_releaseDate",
            ),
        ),
        migrations.AddConstraint(
            model_name="review",
            constraint=models.CheckConstraint(
                condition=models.Q(("date__lte", datetime.date(2025, 1, 25))),
                name="CK_Review_date",
            ),
        ),
    ]
