# Generated by Django 5.1.5 on 2025-01-17 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_appuser_last_login"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appuser",
            name="email",
            field=models.EmailField(
                db_column="email", max_length=320, primary_key=True, serialize=False
            ),
        ),
    ]
