# Generated by Django 5.1.5 on 2025-01-17 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_alter_appuser_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appuser",
            name="password",
            field=models.CharField(db_column="password", max_length=128),
        ),
    ]
