# Generated by Django 5.1.5 on 2025-01-21 18:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_remove_appuser_issuperuser"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="car",
            name="CK_Car_releaseDate",
        ),
        migrations.RemoveConstraint(
            model_name="review",
            name="CK_Review_date",
        ),
        migrations.AddConstraint(
            model_name="car",
            constraint=models.CheckConstraint(
                condition=models.Q(("releaseDate__lte", datetime.date(2025, 1, 21))),
                name="CK_Car_releaseDate",
            ),
        ),
        migrations.AddConstraint(
            model_name="review",
            constraint=models.CheckConstraint(
                condition=models.Q(("date__lte", datetime.date(2025, 1, 21))),
                name="CK_Review_date",
            ),
        ),
    ]
