# Generated by Django 5.1.5 on 2025-01-22 08:31

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_remove_car_ck_car_releasedate_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CarImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="cars/images/")),
            ],
            options={
                "db_table": "CarImage",
            },
        ),
        migrations.RemoveConstraint(
            model_name="car",
            name="CK_Car_releaseDate",
        ),
        migrations.RemoveConstraint(
            model_name="review",
            name="CK_Review_date",
        ),
        migrations.AddConstraint(
            model_name="car",
            constraint=models.CheckConstraint(
                condition=models.Q(("releaseDate__lte", datetime.date(2025, 1, 22))),
                name="CK_Car_releaseDate",
            ),
        ),
        migrations.AddConstraint(
            model_name="review",
            constraint=models.CheckConstraint(
                condition=models.Q(("date__lte", datetime.date(2025, 1, 22))),
                name="CK_Review_date",
            ),
        ),
        migrations.AddField(
            model_name="carimage",
            name="car",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="app.car",
            ),
        ),
    ]
