# Generated by Django 5.1.5 on 2025-01-22 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_carimage_remove_car_ck_car_releasedate_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="image",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="image",
            name="id",
            field=models.AutoField(db_column="id", primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name="image",
            unique_together={("id", "image", "modelNameCar")},
        ),
        migrations.DeleteModel(
            name="CarImage",
        ),
    ]
