# Generated by Django 5.1.5 on 2025-01-23 13:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_remove_car_ck_car_releasedate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="modification",
            name="emailUserManages",
            field=models.ForeignKey(
                db_column="emailUserManages",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="managedModifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
