# Generated by Django 5.1.5 on 2025-01-23 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0012_alter_modification_emailusermanages"),
    ]

    operations = [
        migrations.AddField(
            model_name="appuser",
            name="isSuperUser",
            field=models.BooleanField(db_column="isSuperUser", default=False),
        ),
    ]
