# Generated by Django 5.1.5 on 2025-01-23 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0013_appuser_issuperuser"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appuser",
            name="isSuperUser",
        ),
    ]
